databases:
  - name: url_shortener_db
    databaseName: url_shortener
    user: url_shortener_user
    plan: free  # Free tier database

services:
  - type: web
    name: url-shortener-api
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd backend && alembic upgrade head
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: url_shortener_db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src
    plan: free
